# Generated by Django 3.1.7 on 2021-09-26 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_last_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='last_message',
        ),
    ]
